# Generated by Django 3.0.6 on 2020-05-18 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(blank=True, default=False)),
                ('company', models.CharField(blank=True, max_length=40, null=True)),
                ('team', models.CharField(blank=True, max_length=50, null=True)),
                ('from_admin', models.CharField(blank=True, max_length=30, null=True)),
                ('task_type', models.CharField(blank=True, max_length=1024, null=True)),
                ('deadline', models.CharField(blank=True, max_length=30, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('example', models.CharField(blank=True, max_length=200, null=True)),
                ('more', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Tasks')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Team')),
            ],
        ),
    ]
