# Generated by Django 3.0.6 on 2020-05-05 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('example', models.CharField(blank=True, max_length=200, null=True)),
                ('more', models.CharField(blank=True, max_length=1024, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('from_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Staff')),
                ('task_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='company.TaskType')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
