# Generated by Django 3.0.6 on 2020-05-05 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200505_1921'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='from_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Admins'),
        ),
    ]
