# Generated by Django 3.0.6 on 2020-05-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200505_1921'),
        ('task', '0002_auto_20200505_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CompletedTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Tasks')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
