# Generated by Django 3.0.6 on 2020-05-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_tasks_mention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='example',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='mention',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
