# Generated by Django 3.0.6 on 2020-05-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20200519_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
