# Generated by Django 3.0.6 on 2020-05-09 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_unknown'),
        ('task', '0006_auto_20200507_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='company.Team'),
        ),
    ]
