# Generated by Django 3.0.6 on 2020-05-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20200509_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='company',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='from_admin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_type',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='team',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
