# Generated by Django 3.0.6 on 2020-05-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20200519_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtasks',
            name='completed_id',
            field=models.IntegerField(default=0),
        ),
    ]
