# Generated by Django 3.0.6 on 2020-05-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20200517_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
