# Generated by Django 3.0.6 on 2020-05-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20200519_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtasks',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
