# Generated by Django 3.0.6 on 2020-05-05 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='is_admin',
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Staff')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
