# Generated by Django 3.0.6 on 2020-05-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktype',
            name='team',
        ),
    ]
