# Generated by Django 3.0.6 on 2020-05-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200505_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='posts',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
