# Generated by Django 3.0.6 on 2020-05-18 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_tasktype_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='teamname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Team'),
        ),
    ]
