# Generated by Django 3.0.6 on 2020-05-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200506_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='tg_id',
            field=models.IntegerField(null=True),
        ),
    ]
