# Generated by Django 3.0.6 on 2020-05-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20200506_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='tg_id',
            new_name='telegram_id',
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
