# Generated by Django 3.0.6 on 2020-05-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20200506_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='telegram_id',
            field=models.IntegerField(null=True),
        ),
    ]
