# Generated by Django 3.0.6 on 2020-05-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20200506_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='first_name',
        ),
    ]
