# Generated by Django 3.0.6 on 2020-05-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20200507_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
