# Generated by Django 3.0.6 on 2020-05-18 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_unknown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktype',
            name='user',
        ),
        migrations.AddField(
            model_name='tasktype',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.Team'),
        ),
    ]
